use_default_settings:
  engines:
    remove:
      - ahmia
      - torch
      - radio browser

general:
  debug: false
  donation_url: false
  contact_url: false
  privacypolicy_url: false
  enable_metrics: false
  default_doi_resolver: "oadoi.org"

server:
  base_url: http://localhost:8080/
  secret_key: "be6a3e7957e148494eee4ce9c809e411011b7ad0aaa9e715be0e9a6b66255dea"
  limiter: false
  image_proxy: false
  real_ip:
    x_for: 0

search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""
  formats:
    - html
    - json

ui:
  static_use_hash: true

botdetection:
  ip_limit:
    enabled: false
  ip_lists:
    enabled: false

